;
; Story lines for story 1 of bam
;
; Compressed string "THE REMAINS OF HIS FINAL"
bam_story1_line1
	.byte	075h,06ah,006h,0b3h,0e9h,08ah,0eah,04bh
	.byte	007h,0f0h,019h,0a4h,02ah,01dh,09ch,0eah
	.byte	02bh,0b6h,000h
	.even

; Compressed string "OPPONENTS COOLED DOWN TO"
bam_story1_line2
	.byte	070h,01ch,0c3h,0afh,0f9h,0d6h,074h,040h
	.byte	0c2h,070h,06bh,096h,041h,009h,0e3h,06fh
	.byte	050h,0c3h,000h
	.even

; Compressed string "SMOLDERING ASHES. HOWEVER, BAM"
bam_story1_line3
	.byte	0b4h,00bh,0b7h,0a5h,039h,0abh,02fh,01ah
	.byte	088h,074h,06ah,0d2h,04fh,090h,0c2h,0b8h
	.byte	079h,09bh,073h,013h,08ch,0a2h,00bh,000h
	.even

; Compressed string "BAM DID NOT.  STILL FIRED UP"
bam_story1_line4
	.byte	0a3h,0e8h,006h,0a5h,05ah,006h,02fh,05ch
	.byte	03fh,041h,040h,0d7h,06ah,0dbh,006h,0a7h
	.byte	03ah,09bh,065h,060h,0c7h,000h
	.even

; Compressed string "FROM THE HEAT OF BATTLE WITH"
bam_story1_line5
	.byte	0e7h,00ch,0bbh,041h,09dh,09ah,041h,06ah
	.byte	08ah,075h,000h,09fh,0c1h,028h,0d6h,075h
	.byte	06bh,006h,0b8h,05ah,0a7h,000h
	.even

; Compressed string "EYES GLARING, CHEST HEAVING, AND"
bam_story1_line6
	.byte	0a6h,06eh,0d2h,001h,0dah,08ah,0b3h,0fah
	.byte	0a2h,04dh,040h,0a6h,026h,05dh,007h,0a9h
	.byte	029h,0deh,0eah,08bh,036h,081h,0f8h,096h
	.byte	000h
	.even

; Compressed string "LICKS OF FLAME DANCING UP FROM"
bam_story1_line7
	.byte	0adh,04ah,0b2h,074h,000h,09fh,0c1h,0d9h
	.byte	08ah,0aeh,019h,094h,0e2h,04bh,0aah,02fh
	.byte	01ah,0d8h,071h,070h,0ceh,0b0h,00bh,000h
	.even

; Compressed string "HIS HANDS, BAM BAM TURNED TO THE"
bam_story1_line8
	.byte	0a9h,04ah,007h,0a9h,0f8h,096h,074h,013h
	.byte	08ch,0a2h,01bh,08ch,0a2h,01bh,0d4h,0f6h
	.byte	0fch,09ah,065h,050h,0c3h,041h,09dh,09ah
	.byte	000h
	.even

; Compressed string "AUDIENCE AND DELIVERED A"
bam_story1_line9
	.byte	0a2h,05dh,0aah,0e6h,04bh,09ah,081h,0f8h
	.byte	096h,041h,069h,0b6h,0eah,06dh,0ceh,066h
	.byte	019h,088h,000h
	.even

; Compressed string "VIGILANT STARE.  HIS EYES"
bam_story1_line10
	.byte	0b7h,08ah,0aah,0adh,0f8h,0d6h,001h,05dh
	.byte	08bh,0b3h,0f9h,004h,041h,0aah,0d2h,081h
	.byte	0a9h,09bh,034h,000h
	.even

; Compressed string "SCANNED BACK AND FORTH AND A"
bam_story1_line11
	.byte	034h,029h,0beh,0afh,059h,006h,0a3h,048h
	.byte	0b2h,081h,0f8h,096h,0c1h,009h,0cfh,075h
	.byte	01ah,088h,06fh,019h,088h,000h
	.even

; Compressed string "SINISTER SMILE CREPT ACROSS HIS"
bam_story1_line12
	.byte	0b4h,0fah,0aah,074h,06dh,0ceh,001h,0edh
	.byte	0aah,0adh,019h,090h,0b3h,019h,0d7h,081h
	.byte	048h,0ceh,030h,04dh,007h,0a9h,04ah,003h
	.even

; Compressed string "FACE.  HE RAISED HIS HANDS AND"
bam_story1_line13
	.byte	0a7h,048h,09ah,04fh,010h,0a4h,066h,030h
	.byte	08bh,02ah,06dh,096h,041h,0aah,0d2h,041h
	.byte	02ah,0beh,025h,01dh,088h,06fh,009h,000h
	.even

; Compressed string "WITHOUT WARNING CAME A BLAST OF"
bam_story1_line14
	.byte	0b8h,05ah,0a7h,0b0h,05dh,007h,0b8h,038h
	.byte	0bfh,0eah,08bh,006h,0a4h,0e8h,09ah,081h
	.byte	018h,08ch,0adh,048h,0d7h,001h,07ch,002h
	.even

; Compressed string "FLAMES WHICH ENGULFED THE ENTIRE"
bam_story1_line15
	.byte	067h,02bh,0bah,026h,01dh,0e0h,0a9h,04ah
	.byte	0a6h,081h,0f9h,0a2h,076h,07bh,09ah,065h
	.byte	050h,0a7h,066h,060h,0beh,0b5h,03ah,09bh
	.byte	000h
	.even

; Compressed string "STADIUM.  THE AUDIENCE WAS"
bam_story1_line16
	.byte	074h,02dh,096h,0aah,0edh,03eh,041h,050h
	.byte	0a7h,066h,020h,0dah,0a5h,06ah,0beh,0a4h
	.byte	019h,0e0h,022h,00dh,000h
	.even

; Compressed string "CHARRED TO FLAKES, THE STADIUM"
bam_story1_line17
	.byte	064h,02ah,0ceh,0b3h,059h,006h,035h,01ch
	.byte	09ch,0adh,0c8h,09ah,074h,013h,0d4h,0a9h
	.byte	019h,0d0h,0b5h,058h,0aah,0b6h,00bh,000h
	.even

; Compressed string "WAS REDUCED TO PEBBLES, AND THE"
bam_story1_line18
	.byte	0b8h,048h,007h,0b3h,059h,0dah,0a4h,059h
	.byte	006h,035h,01ch,0c4h,0e6h,038h,0b6h,026h
	.byte	0ddh,004h,0e2h,05bh,006h,075h,06ah,002h
	.even

; Compressed string "WWF TITLE BELONGED TO BAM BAM"
bam_story1_line19
	.byte	038h,07eh,006h,0b5h,05ah,0b7h,066h,030h
	.byte	09ah,02dh,0fch,0a2h,066h,019h,0d4h,070h
	.byte	030h,08ah,06eh,030h,08ah,02eh,000h
	.even

; Compressed string "BIGELOW.  THE UNDISPUTED"
bam_story1_line20
	.byte	0a3h,08ah,09ah,02dh,08ch,03fh,041h,050h
	.byte	0a7h,066h,060h,0bfh,0a5h,04ah,0c7h,076h
	.byte	06dh,096h,000h
	.even

; Compressed string "CHAMPION STOOD AMONG THE SILENT"
bam_story1_line21
	.byte	064h,02ah,0bah,0b1h,00ah,0bfh,001h,05dh
	.byte	0c3h,070h,019h,088h,02eh,0fch,0a2h,041h
	.byte	09dh,09ah,001h,0adh,0b6h,0e6h,05bh,003h
	.even

; Compressed string "RUINS OF THE NOW SHATTERED"
bam_story1_line22
	.byte	0b3h,0adh,0beh,074h,000h,09fh,041h,09dh
	.byte	09ah,0c1h,00bh,0e3h,001h,09dh,08ah,075h
	.byte	06dh,0ceh,066h,009h,000h
	.even

; Compressed string "AMPITHEATER, MASTER OF ALL HE"
bam_story1_line23
	.byte	0a2h,01bh,0abh,075h,06ah,08ah,0b5h,039h
	.byte	037h,081h,02bh,0d2h,0b5h,039h,007h,0f0h
	.byte	019h,088h,06dh,01bh,0a4h,026h,000h
	.even

; Compressed string "SURVEYED."
bam_story1_line24
	.byte	0b4h,03dh,0dfh,0a6h,06eh,096h,00fh,000h
	.even

;
; Story line table for Story 1 of bam
;
bam_story_tbl1
	.long	bam_story1_line1
	.long	bam_story1_line2
	.long	bam_story1_line3
	.long	bam_story1_line4
	.long	bam_story1_line5
	.long	bam_story1_line6
	.long	bam_story1_line7
	.long	bam_story1_line8
	.long	bam_story1_line9
	.long	bam_story1_line10
	.long	bam_story1_line11
	.long	bam_story1_line12
	.long	bam_story1_line13
	.long	bam_story1_line14
	.long	bam_story1_line15
	.long	bam_story1_line16
	.long	bam_story1_line17
	.long	bam_story1_line18
	.long	bam_story1_line19
	.long	bam_story1_line20
	.long	bam_story1_line21
	.long	bam_story1_line22
	.long	bam_story1_line23
	.long	bam_story1_line24
	.long	0

;
; Table of stories for bam
;
bam_stories
	.long	bam_story_tbl1

