;
; Story lines for story 1 of bret
;
; Compressed string "THROUGH THE EXCELLENCE OF"
bret_story1_line1
	.byte	075h,03ah,0c3h,036h,09ah,006h,075h,06ah
	.byte	006h,066h,04eh,09ah,06dh,06bh,0beh,0a4h
	.byte	019h,0c0h,027h,000h
	.even

; Compressed string "EXECUTION, BRET FINISHED OFF THE"
bret_story1_line2
	.byte	066h,06eh,092h,076h,0adh,0c2h,06fh,013h
	.byte	08ch,0b3h,059h,007h,0a7h,0fah,0aah,074h
	.byte	06ah,096h,001h,07ch,09eh,041h,09dh,09ah
	.byte	000h
	.even

; Compressed string "LAST OF THE BUNCH.  HIS VICTORY"
bret_story1_line3
	.byte	0adh,048h,0d7h,001h,07ch,006h,075h,06ah
	.byte	006h,0a3h,0fdh,092h,0e9h,013h,004h,0a9h
	.byte	04ah,007h,0b7h,04ah,0d6h,0f0h,0ach,003h
	.even

; Compressed string "MADE NEWSPAPER AND MAGAZINE"
bret_story1_line4
	.byte	0aeh,058h,09ah,0c1h,06bh,0e2h,074h,02ch
	.byte	0c6h,0e6h,01ch,088h,06fh,019h,0b8h,022h
	.byte	02ah,0eeh,0eah,06bh,002h
	.even

; Compressed string "HEADLINES THROUGHOUT THE WORLD"
bret_story1_line5
	.byte	0a9h,029h,096h,0adh,0fah,09ah,074h,050h
	.byte	0a7h,033h,06ch,0a3h,029h,06ch,0d7h,041h
	.byte	09dh,09ah,001h,00eh,0cfh,06dh,009h,000h
	.even

; Compressed string "AND BRET'S POPULARITY GREW TO"
bret_story1_line6
	.byte	0e2h,05bh,006h,0e3h,06ch,0d6h,008h,01dh
	.byte	0c4h,070h,06ch,0b7h,0e2h,0ach,0d6h,07ah
	.byte	080h,0ceh,026h,01eh,0d4h,030h,000h
	.even

; Compressed string "OUTRAGEOUS PROPORTIONS. WHILE"
bret_story1_line7
	.byte	0b0h,05dh,0cfh,022h,06ah,0c2h,036h,01dh
	.byte	0c4h,033h,01ch,0c3h,073h,0adh,0c2h,02fh
	.byte	0fdh,004h,078h,0aah,0b6h,026h,000h
	.even

; Compressed string "DEFENDING HIS TITLE FOR FIVE"
bret_story1_line8
	.byte	0a5h,079h,09ah,06fh,0a9h,0beh,068h,090h
	.byte	0aah,074h,050h,0abh,075h,06bh,006h,027h
	.byte	03ch,007h,0a7h,07ah,09bh,000h
	.even

; Compressed string "YEARS STRAIGHT, HE BECAME A STAR"
bret_story1_line9
	.byte	0bah,029h,0ceh,074h,040h,0d7h,0b3h,0a8h
	.byte	0a2h,069h,0ddh,004h,0a9h,019h,08ch,026h
	.byte	029h,0bah,066h,020h,006h,074h,02dh,0ceh
	.byte	000h
	.even

; Compressed string "OF STAGE AND SCREEN AS WELL AS"
bret_story1_line10
	.byte	0f0h,019h,0d0h,0b5h,088h,09ah,081h,0f8h
	.byte	096h,001h,04dh,0ceh,0a6h,0f9h,006h,022h
	.byte	01dh,0e0h,066h,0dbh,006h,022h,00dh,000h
	.even

; Compressed string "THE RING, APPEARING IN SEVERAL"
bret_story1_line11
	.byte	075h,06ah,006h,0b3h,0fah,0a2h,04dh,020h
	.byte	0c6h,0b1h,029h,0ceh,0eah,08bh,006h,0eah
	.byte	01bh,0d0h,0e6h,06dh,0ceh,062h,00bh,000h
	.even

; Compressed string "WEEKLY TELEVISION DRAMAS AND"
bret_story1_line12
	.byte	0b8h,069h,0b2h,0adh,01eh,0d4h,066h,06bh
	.byte	0deh,02ah,0adh,0c2h,06fh,050h,0ceh,0a2h
	.byte	02bh,0d2h,081h,0f8h,096h,000h
	.even

; Compressed string "BROADWAY PRODUCTIONS. "
bret_story1_line13
	.byte	0e3h,00ch,08bh,025h,02eh,0eah,041h,03ch
	.byte	0c3h,0a5h,04dh,0d6h,02ah,0fch,0d2h,04fh
	.byte	000h,000h
	.even

; Compressed string "UNBEATABLE, HE RETIRED AS"
bret_story1_line14
	.byte	0f6h,03bh,09ah,062h,02dh,08eh,0adh,0d9h
	.byte	004h,0a9h,019h,0cch,066h,0adh,0ceh,066h
	.byte	019h,088h,034h,000h
	.even

; Compressed string "CHAMPION TO PURSUE A BIG SCREEN"
bret_story1_line15
	.byte	064h,02ah,0bah,0b1h,00ah,0bfh,041h,00dh
	.byte	007h,0b1h,03dh,0d3h,0b6h,019h,088h,0c1h
	.byte	0a8h,0a2h,001h,04dh,0ceh,0a6h,0f9h,002h
	.even

; Compressed string "CAREER IN ITALY, WHERE HE BECAME"
bret_story1_line16
	.byte	0a4h,038h,09bh,0e6h,01ch,0a8h,06fh,0a0h
	.byte	0d6h,062h,0abh,037h,001h,09eh,09ah,0b3h
	.byte	019h,0a4h,066h,030h,09ah,0a4h,0e8h,09ah
	.byte	000h
	.even

; Compressed string "THE GRATEST SPAGHETTI-WESTERN"
bret_story1_line17
	.byte	075h,06ah,006h,0e8h,02ch,0d6h,026h,05dh
	.byte	007h,074h,02ch,0a2h,0a9h,059h,0d7h,0aah
	.byte	083h,09bh,074h,06dh,0ceh,02fh,000h
	.even

; Compressed string "STAR IN FILM HISTORY, WINNING SIX"
bret_story1_line18
	.byte	074h,02dh,0ceh,081h,0fah,006h,0a7h,0dah
	.byte	0bah,041h,0aah,0d2h,035h,03ch,0ebh,04dh
	.byte	080h,0abh,0efh,0abh,0beh,068h,040h,0abh
	.byte	039h,000h
	.even

; Compressed string "ACADEMY AWARDS OVER HIS LIFETIME,"
bret_story1_line19
	.byte	022h,029h,096h,0a6h,0abh,007h,022h,02eh
	.byte	0ceh,025h,01dh,0c0h,0b7h,039h,007h,0a9h
	.byte	04ah,007h,0adh,07ah,09ah,0b5h,0eah,09ah
	.byte	00dh,000h
	.even

; Compressed string "AND GROSSING OVER 300 MILLION"
bret_story1_line20
	.byte	0e2h,05bh,006h,0e8h,00ch,0d3h,0b4h,0fah
	.byte	0a2h,001h,07ch,09bh,073h,040h,045h,051h
	.byte	0e0h,0aah,06dh,0abh,0c2h,02fh,000h
	.even

; Compressed string "DOLLARS ON EACH OF HIS FILMS."
bret_story1_line21
	.byte	025h,0dch,0b6h,0e2h,04ch,007h,0f0h,01bh
	.byte	098h,022h,099h,006h,0f0h,019h,0a4h,02ah
	.byte	01dh,09ch,06ah,0ebh,0d2h,00fh,000h
	.even

;
; Story line table for Story 1 of bret
;
bret_story_tbl1
	.long	bret_story1_line1
	.long	bret_story1_line2
	.long	bret_story1_line3
	.long	bret_story1_line4
	.long	bret_story1_line5
	.long	bret_story1_line6
	.long	bret_story1_line7
	.long	bret_story1_line8
	.long	bret_story1_line9
	.long	bret_story1_line10
	.long	bret_story1_line11
	.long	bret_story1_line12
	.long	bret_story1_line13
	.long	bret_story1_line14
	.long	bret_story1_line15
	.long	bret_story1_line16
	.long	bret_story1_line17
	.long	bret_story1_line18
	.long	bret_story1_line19
	.long	bret_story1_line20
	.long	bret_story1_line21
	.long	0

;
; Table of stories for bret
;
bret_stories
	.long	bret_story_tbl1

