;
; Story lines for story 1 of lex
;
; Compressed string "A STAR SPANGLED CELEBRATION FOR"
lex_story1_line1
	.byte	062h,040h,0d7h,0e2h,01ch,0d0h,0b1h,0f8h
	.byte	0a2h,0adh,059h,006h,0a4h,0d9h,09ah,0e3h
	.byte	02ch,0d6h,02ah,0fch,006h,027h,03ch,003h
	.even

; Compressed string "THE ULTIMATE AMERICAN SYMBOL. "
lex_story1_line2
	.byte	075h,06ah,006h,076h,05bh,0abh,0aeh,058h
	.byte	09bh,081h,0e8h,09ah,0b3h,04ah,08ah,06fh
	.byte	040h,0ebh,0eeh,008h,0b7h,04fh,000h,000h
	.even

; Compressed string "LEX LUGER'S VICTORY WAS"
lex_story1_line3
	.byte	0adh,099h,007h,0adh,08dh,09ah,033h,042h
	.byte	007h,0b7h,04ah,0d6h,0f0h,0ach,007h,0b8h
	.byte	048h,003h
	.even

; Compressed string "RENOWNED THROUGHOUT THE COUNTRY"
lex_story1_line4
	.byte	0b3h,0f9h,0c2h,0f8h,06bh,096h,041h,09dh
	.byte	0ceh,0b0h,08dh,0a6h,0b0h,05dh,007h,075h
	.byte	06ah,006h,024h,06ch,0bfh,0f5h,0ach,003h
	.even

; Compressed string "AND WAS RECOGNIZED AS ONE OF"
lex_story1_line5
	.byte	0e2h,05bh,006h,0b8h,048h,007h,0b3h,049h
	.byte	0c2h,0e8h,0abh,0eeh,066h,019h,088h,074h
	.byte	000h,0bfh,066h,000h,09fh,000h
	.even

; Compressed string "THE GREATEST TRIUMPHS OF THE"
lex_story1_line6
	.byte	075h,06ah,006h,0e8h,06ch,08ah,0b5h,049h
	.byte	0d7h,041h,03dh,0abh,0b6h,01bh,0a7h,074h
	.byte	000h,09fh,041h,09dh,09ah,000h
	.even

; Compressed string "20TH CENTURY.  A NEW NATIONAL"
lex_story1_line7
	.byte	053h,054h,0a7h,001h,069h,0beh,0b5h,03dh
	.byte	0ebh,04fh,010h,088h,0c1h,06bh,0e2h,0c1h
	.byte	02bh,0d6h,02ah,0fch,08ah,02dh,000h
	.even

; Compressed string "HOLIDAY WAS NAMED, AND PEOPLE"
lex_story1_line8
	.byte	029h,0dch,0aah,0a5h,0a8h,007h,0b8h,048h
	.byte	007h,0afh,0e8h,09ah,065h,013h,088h,06fh
	.byte	019h,0c4h,026h,01ch,0b7h,026h,000h
	.even

; Compressed string "EVERYWHERE FROM COAST TO COAST"
lex_story1_line9
	.byte	0e6h,06dh,0ceh,03ah,09eh,09ah,0b3h,019h
	.byte	09ch,033h,0ech,006h,024h,02ch,0d2h,075h
	.byte	050h,0c3h,001h,009h,08bh,074h,00dh,000h
	.even

; Compressed string "THREW OPEN THEIR WINDOWS AND"
lex_story1_line10
	.byte	075h,03ah,09bh,078h,000h,0c7h,0e6h,01bh
	.byte	0d4h,0a9h,0a9h,0ceh,001h,0aeh,0beh,025h
	.byte	08ch,0d3h,081h,0f8h,096h,000h
	.even

; Compressed string "CHANTED HIS NAME.  THIS WAS"
lex_story1_line11
	.byte	064h,02ah,0beh,0b5h,059h,006h,0a9h,04ah
	.byte	007h,0afh,0e8h,09ah,04fh,010h,0d4h,0a9h
	.byte	04ah,007h,0b8h,048h,003h
	.even

; Compressed string "MORE THAN JUST A VICTORY FOR"
lex_story1_line12
	.byte	02eh,03ch,09bh,041h,09dh,08ah,06fh,0b0h
	.byte	0dah,074h,01dh,088h,0c1h,0adh,092h,035h
	.byte	03ch,0ebh,0c1h,009h,0cfh,000h
	.even

; Compressed string "LEX, IT WAS A VICTORY THE GOOD"
lex_story1_line13
	.byte	0adh,099h,037h,081h,05ah,007h,0b8h,048h
	.byte	007h,062h,070h,0abh,064h,00dh,0cfh,07ah
	.byte	050h,0a7h,066h,080h,0c2h,070h,009h,000h
	.even

; Compressed string "OL' U.S. OF A.. AMERICANS COULD"
lex_story1_line14
	.byte	070h,08bh,004h,0f6h,043h,03fh,001h,07ch
	.byte	006h,0e2h,0f3h,004h,0a2h,06bh,0ceh,02ah
	.byte	029h,0beh,074h,040h,0c2h,076h,05bh,002h
	.even

; Compressed string "ONCE AGAIN HOLD THEIR HEADS"
lex_story1_line15
	.byte	0f0h,04bh,09ah,081h,088h,08ah,0eah,01bh
	.byte	0a4h,070h,05bh,006h,075h,06ah,0aah,073h
	.byte	090h,09ah,062h,049h,003h
	.even

; Compressed string "HIGH AND STAND PROUD. LEX"
lex_story1_line16
	.byte	0a9h,08ah,0a6h,081h,0f8h,096h,001h,05dh
	.byte	08bh,06fh,019h,0c4h,033h,06ch,097h,04fh
	.byte	0d0h,09ah,039h,000h
	.even

; Compressed string "REPRESENTS ALL THE PEOPLE IN"
lex_story1_line17
	.byte	0b3h,019h,0cfh,026h,06dh,0beh,035h,01dh
	.byte	088h,06dh,01bh,0d4h,0a9h,019h,0c4h,026h
	.byte	01ch,0b7h,066h,0a0h,0beh,000h
	.even

; Compressed string "THIS GREAT LAND.  WHEN HE"
lex_story1_line18
	.byte	075h,0aah,0d2h,001h,03ah,09bh,062h,01dh
	.byte	0b4h,0e2h,05bh,03eh,041h,080h,0a7h,0e6h
	.byte	01bh,0a4h,026h,000h
	.even

; Compressed string "TOURED THE UNITED STATES IN HIS"
lex_story1_line19
	.byte	035h,06ch,0cfh,066h,019h,0d4h,0a9h,019h
	.byte	0d8h,0afh,05ah,09bh,065h,040h,0d7h,062h
	.byte	06dh,0d2h,081h,0fah,006h,0a9h,04ah,003h
	.even

; Compressed string "<LEX EXPRESS>, HE BROUGHT BACK"
lex_story1_line20
	.byte	05dh,06bh,0e6h,081h,099h,0c7h,0b3h,049h
	.byte	0d3h,05fh,013h,0a4h,066h,030h,0ceh,0b0h
	.byte	08dh,0a6h,075h,030h,08ah,024h,00bh,000h
	.even

; Compressed string "A PIECE OF EVERY PERSON IN"
lex_story1_line21
	.byte	062h,010h,0abh,026h,069h,006h,0f0h,019h
	.byte	098h,0b7h,039h,0ebh,041h,06ch,0ceh,034h
	.byte	0fch,006h,0eah,00bh,000h
	.even

; Compressed string "EVERY TOWN HE VISITED.  LEX"
lex_story1_line22
	.byte	0e6h,06dh,0ceh,07ah,050h,0c3h,0f8h,01bh
	.byte	0a4h,066h,070h,0abh,0b4h,05ah,09bh,0e5h
	.byte	013h,004h,0adh,099h,003h
	.even

; Compressed string "VIEWS HIMSELF AS THE PRODUCT OF"
lex_story1_line23
	.byte	0b7h,06ah,0e2h,074h,090h,0aah,02eh,06dh
	.byte	0b6h,067h,020h,0d2h,041h,09dh,09ah,041h
	.byte	03ch,0c3h,0a5h,04dh,0d6h,001h,07ch,002h
	.even

; Compressed string "ALL AMERICANS WHO, IN HIS MIND,"
lex_story1_line24
	.byte	062h,0dbh,006h,0a2h,06bh,0ceh,02ah,029h
	.byte	0beh,074h,080h,0a7h,070h,013h,0a8h,06fh
	.byte	090h,0aah,074h,0e0h,0aah,06fh,0d9h,000h
	.even

; Compressed string "MADE HIM WHAT HE IS: AMERICA'S"
lex_story1_line25
	.byte	0aeh,058h,09ah,041h,0aah,0bah,001h,09eh
	.byte	08ah,075h,090h,09ah,081h,04ah,06fh,081h
	.byte	0e8h,09ah,0b3h,04ah,08ah,008h,00dh,000h
	.even

; Compressed string "<ALL AMERICAN.>"
lex_story1_line26
	.byte	09dh,0d8h,0b6h,081h,0e8h,09ah,0b3h,04ah
	.byte	08ah,0efh,0f3h,001h
	.even

;
; Story line table for Story 1 of lex
;
lex_story_tbl1
	.long	lex_story1_line1
	.long	lex_story1_line2
	.long	lex_story1_line3
	.long	lex_story1_line4
	.long	lex_story1_line5
	.long	lex_story1_line6
	.long	lex_story1_line7
	.long	lex_story1_line8
	.long	lex_story1_line9
	.long	lex_story1_line10
	.long	lex_story1_line11
	.long	lex_story1_line12
	.long	lex_story1_line13
	.long	lex_story1_line14
	.long	lex_story1_line15
	.long	lex_story1_line16
	.long	lex_story1_line17
	.long	lex_story1_line18
	.long	lex_story1_line19
	.long	lex_story1_line20
	.long	lex_story1_line21
	.long	lex_story1_line22
	.long	lex_story1_line23
	.long	lex_story1_line24
	.long	lex_story1_line25
	.long	lex_story1_line26
	.long	0

;
; Table of stories for lex
;
lex_stories
	.long	lex_story_tbl1

