;
; Story lines for story 1 of shawn
;
; Compressed string "SHAWN STRUTTED AROUND THE RING"
shawn_story1_line1
	.byte	074h,02ah,0e2h,06fh,040h,0d7h,0b3h,05dh
	.byte	0d7h,066h,019h,088h,033h,06ch,0bfh,065h
	.byte	050h,0a7h,066h,030h,0abh,02fh,00ah,000h
	.even

; Compressed string "ARROGANTLY FOR SEVERAL MINUTES,"
shawn_story1_line2
	.byte	0e2h,03ch,0c3h,0a8h,0f8h,0d6h,0adh,01eh
	.byte	09ch,0f0h,01ch,0d0h,0e6h,06dh,0ceh,062h
	.byte	01bh,0b8h,0eah,06bh,0d7h,026h,0ddh,000h
	.even

; Compressed string "FLEXING AND CHEWING HIS GUM WITH"
shawn_story1_line3
	.byte	067h,06bh,0e6h,0eah,08bh,006h,0e2h,05bh
	.byte	006h,064h,06ah,0e2h,0eah,08bh,006h,0a9h
	.byte	04ah,007h,0a8h,0edh,006h,0b8h,05ah,0a7h
	.byte	000h
	.even

; Compressed string "AN OBNOXIOUS SMIRK ON HIS FACE. "
shawn_story1_line4
	.byte	0e2h,01bh,0c0h,0e3h,00bh,0e7h,02ah,06ch
	.byte	0d3h,001h,0edh,0aah,033h,01bh,0c0h,06fh
	.byte	090h,0aah,074h,070h,08ah,0a4h,0f9h,004h
	.byte	000h
	.even

; Compressed string "HE HAD ALWAYS BRAGGED THAT HE"
shawn_story1_line5
	.byte	0a9h,019h,0a4h,062h,019h,088h,02dh,02eh
	.byte	0eah,074h,030h,0ceh,022h,08ah,09ah,065h
	.byte	050h,0a7h,062h,01dh,0a4h,026h,000h
	.even

; Compressed string "WAS THE GREATEST THING TO GRACE"
shawn_story1_line6
	.byte	0b8h,048h,007h,075h,06ah,006h,0e8h,06ch
	.byte	08ah,0b5h,049h,0d7h,041h,09dh,0aah,02fh
	.byte	01ah,0d4h,070h,080h,0ceh,022h,069h,002h
	.even

; Compressed string "THE WORLD WRESTLING FEDERATION,"
shawn_story1_line7
	.byte	075h,06ah,006h,038h,03ch,0b7h,065h,080h
	.byte	0cfh,026h,05dh,0b7h,0eah,08bh,006h,0a7h
	.byte	059h,09ah,0b3h,058h,0abh,0f0h,0dbh,000h
	.even

; Compressed string "AND NOW HE HAS FINALLY PROVEN"
shawn_story1_line8
	.byte	0e2h,05bh,006h,02fh,08ch,007h,0a9h,019h
	.byte	0a4h,022h,01dh,09ch,0eah,02bh,0b6h,0adh
	.byte	01eh,0c4h,033h,07ch,09bh,02fh,000h
	.even

; Compressed string "IT.  THE LADIES IN THE AUDIENCE"
shawn_story1_line9
	.byte	06ah,0fdh,004h,041h,09dh,09ah,041h,02bh
	.byte	096h,0aah,049h,007h,0eah,01bh,0d4h,0a9h
	.byte	019h,088h,076h,0a9h,09ah,02fh,069h,002h
	.even

; Compressed string "REACHED OUT THEIR ARMS TO HIM"
shawn_story1_line10
	.byte	0b3h,029h,092h,0a9h,059h,006h,0b0h,05dh
	.byte	007h,075h,06ah,0aah,073h,020h,0ceh,02eh
	.byte	01dh,0d4h,070h,090h,0aah,02eh,000h
	.even

; Compressed string "AND SCREAMED HIS NAME.  WITH"
shawn_story1_line11
	.byte	0e2h,05bh,006h,034h,039h,09bh,0a2h,06bh
	.byte	096h,041h,0aah,0d2h,0c1h,02bh,0bah,0e6h
	.byte	013h,004h,0b8h,05ah,0a7h,000h
	.even

; Compressed string "THAT, SHAWN THOUGHT HE'D BE CUTE"
shawn_story1_line12
	.byte	075h,02ah,0d6h,04dh,040h,0a7h,022h,0feh
	.byte	006h,075h,00ah,0dbh,068h,05ah,007h,0a9h
	.byte	089h,094h,0c1h,068h,006h,0a4h,05dh,09bh
	.byte	000h
	.even

; Compressed string "BY TEASING THEM WITH A LITTLE"
shawn_story1_line13
	.byte	0a3h,01eh,0d4h,0a6h,048h,0abh,02fh,01ah
	.byte	0d4h,0a9h,0e9h,006h,0b8h,05ah,0a7h,081h
	.byte	018h,0b4h,06ah,05dh,0b7h,026h,000h
	.even

; Compressed string "HIP ACTION. THE LADIES, IN AN"
shawn_story1_line14
	.byte	0a9h,01ah,007h,022h,059h,0abh,0f0h,0fbh
	.byte	004h,075h,06ah,006h,0adh,058h,0aah,026h
	.byte	0ddh,004h,0eah,01bh,088h,02fh,000h
	.even

; Compressed string "UNCONTROLLABLE LUST-CRAZED"
shawn_story1_line15
	.byte	0f6h,04bh,0c2h,06fh,03dh,0c3h,06dh,02bh
	.byte	08eh,0adh,019h,0b4h,036h,05dh,03bh,0e4h
	.byte	02ch,0eeh,066h,009h,000h
	.even

; Compressed string "FRENZY, STAMPEDED THE RING LIKE"
shawn_story1_line16
	.byte	0e7h,06ch,0beh,0bbh,0deh,004h,074h,02dh
	.byte	0bah,0b1h,059h,09ah,065h,050h,0a7h,066h
	.byte	030h,0abh,02fh,01ah,0b4h,02ah,06bh,002h
	.even

; Compressed string "CATTLE, TRYING TO GET HOLD OF"
shawn_story1_line17
	.byte	0a4h,058h,0d7h,0adh,0d9h,004h,0f5h,0ach
	.byte	0abh,02fh,01ah,0d4h,070h,080h,09ah,075h
	.byte	090h,0c2h,06dh,019h,0c0h,027h,000h
	.even

; Compressed string "HIM.  SHAWN SCRAMBLED TO ESCAPE"
shawn_story1_line18
	.byte	0a9h,0eah,03eh,041h,040h,0a7h,022h,0feh
	.byte	006h,034h,039h,08bh,0eeh,0d8h,09ah,065h
	.byte	050h,0c3h,081h,049h,093h,062h,06ch,002h
	.even

; Compressed string "THE CLUTCHES OF THE HORDE, BUT"
shawn_story1_line19
	.byte	075h,06ah,006h,064h,06bh,0d7h,064h,06ah
	.byte	0d2h,001h,07ch,006h,075h,06ah,006h,029h
	.byte	03ch,097h,066h,013h,08ch,076h,00dh,000h
	.even

; Compressed string "TO NO AVAIL.  THEY QUICKLY"
shawn_story1_line20
	.byte	035h,01ch,0bch,070h,020h,0deh,0a2h,0dah
	.byte	03eh,041h,050h,0a7h,0a6h,01eh,0c8h,0b6h
	.byte	04ah,0b2h,0adh,00eh,000h
	.even

; Compressed string "CORNERED HIM AND PROCEEDED TO"
shawn_story1_line21
	.byte	024h,03ch,0bfh,0e6h,06ch,096h,041h,0aah
	.byte	0bah,081h,0f8h,096h,041h,03ch,0c3h,0a4h
	.byte	069h,096h,066h,019h,0d4h,030h,000h
	.even

; Compressed string "RAVAGE HIM, MERCILESSLY.  WHEN"
shawn_story1_line22
	.byte	0b3h,078h,08bh,0a8h,019h,0a4h,0aah,0dbh
	.byte	004h,0aeh,039h,093h,06ah,06bh,0d2h,074h
	.byte	0abh,03fh,041h,080h,0a7h,0e6h,00bh,000h
	.even

; Compressed string "THEY WERE THROUGH, SHAWN WAS"
shawn_story1_line23
	.byte	075h,06ah,0eah,001h,06eh,0ceh,066h,050h
	.byte	0a7h,033h,06ch,0a3h,069h,013h,0d0h,0a9h
	.byte	088h,0bfh,001h,02eh,0d2h,000h
	.even

; Compressed string "LEFT LYING MOTIONLESS, SANS HIS"
shawn_story1_line24
	.byte	0adh,079h,0d6h,041h,0abh,0abh,02fh,01ah
	.byte	0b8h,070h,0adh,0c2h,06fh,06bh,0d2h,074h
	.byte	013h,0d0h,0e2h,04bh,007h,0a9h,04ah,003h
	.even

; Compressed string "CLOTHING AND SOME HAIR, YET WITH"
shawn_story1_line25
	.byte	064h,00bh,0d7h,0a9h,0fah,0a2h,081h,0f8h
	.byte	096h,001h,00dh,0bbh,066h,090h,08ah,0eah
	.byte	0dch,004h,0bah,059h,007h,0b8h,05ah,0a7h
	.byte	000h
	.even

; Compressed string "A  BIG OL' GRIN STAMPED ON HIS"
shawn_story1_line26
	.byte	062h,010h,08ch,02ah,01ah,0c0h,02dh,012h
	.byte	0a0h,0b3h,0fah,006h,074h,02dh,0bah,0b1h
	.byte	059h,006h,0f0h,01bh,0a4h,02ah,00dh,000h
	.even

; Compressed string "FACE.  HE LOVED THE ATTENTION,"
shawn_story1_line27
	.byte	0a7h,048h,09ah,04fh,010h,0a4h,066h,0d0h
	.byte	0c2h,0b7h,059h,006h,075h,06ah,006h,062h
	.byte	05dh,09bh,06fh,0adh,0c2h,06fh,003h,000h
	.even

; Compressed string "AND MORE SO, HE LOVED THE WOMEN."
shawn_story1_line28
	.byte	0e2h,05bh,006h,02eh,03ch,09bh,001h,00dh
	.byte	037h,041h,06ah,006h,02dh,07ch,09bh,065h
	.byte	050h,0a7h,066h,080h,0c3h,0aeh,0f9h,03eh
	.byte	000h
	.even

; Compressed string "HIS CRAVING FOR ATTENTION AND"
shawn_story1_line29
	.byte	0a9h,04ah,007h,0e4h,02ch,0deh,0eah,08bh
	.byte	006h,027h,03ch,007h,062h,05dh,09bh,06fh
	.byte	0adh,0c2h,06fh,020h,0beh,025h,000h
	.even

; Compressed string "MULTIPLE WOMEN LED HIM TO  LEAVE"
shawn_story1_line30
	.byte	0aeh,0ddh,0d6h,06ah,0dch,09ah,001h,00eh
	.byte	0bbh,0e6h,01bh,0b4h,066h,019h,0a4h,0aah
	.byte	01bh,0d4h,070h,010h,0b4h,0a6h,078h,09bh
	.byte	000h
	.even

; Compressed string "WRESTLING AND BECOME A"
shawn_story1_line31
	.byte	0f8h,06ch,0d2h,075h,0abh,0beh,068h,020h
	.byte	0beh,065h,030h,09ah,024h,0ech,09ah,081h
	.byte	008h,000h
	.even

; Compressed string "POLITICIAN, WHERE HE COULD GET"
shawn_story1_line32
	.byte	031h,0dch,0aah,0b5h,04ah,0aah,0e2h,0dbh
	.byte	004h,078h,06ah,0ceh,066h,090h,09ah,001h
	.byte	009h,0dbh,06dh,019h,0a0h,066h,00dh,000h
	.even

; Compressed string "HIS FILL OF BOTH."
shawn_story1_line33
	.byte	0a9h,04ah,007h,0a7h,0dah,0b6h,001h,07ch
	.byte	006h,023h,05ch,0a7h,00fh,000h
	.even

;
; Story line table for Story 1 of shawn
;
shawn_story_tbl1
	.long	shawn_story1_line1
	.long	shawn_story1_line2
	.long	shawn_story1_line3
	.long	shawn_story1_line4
	.long	shawn_story1_line5
	.long	shawn_story1_line6
	.long	shawn_story1_line7
	.long	shawn_story1_line8
	.long	shawn_story1_line9
	.long	shawn_story1_line10
	.long	shawn_story1_line11
	.long	shawn_story1_line12
	.long	shawn_story1_line13
	.long	shawn_story1_line14
	.long	shawn_story1_line15
	.long	shawn_story1_line16
	.long	shawn_story1_line17
	.long	shawn_story1_line18
	.long	shawn_story1_line19
	.long	shawn_story1_line20
	.long	shawn_story1_line21
	.long	shawn_story1_line22
	.long	shawn_story1_line23
	.long	shawn_story1_line24
	.long	shawn_story1_line25
	.long	shawn_story1_line26
	.long	shawn_story1_line27
	.long	shawn_story1_line28
	.long	shawn_story1_line29
	.long	shawn_story1_line30
	.long	shawn_story1_line31
	.long	shawn_story1_line32
	.long	shawn_story1_line33
	.long	0

;
; Table of stories for shawn
;
shawn_stories
	.long	shawn_story_tbl1

