;
; Story lines for story 1 of taker
;
; Compressed string "AFTER THE DUST SETTLED AND THE"
taker_story1_line1
	.byte	0e2h,059h,09bh,073h,050h,0a7h,066h,050h
	.byte	0dah,074h,01dh,0d0h,066h,05dh,0b7h,066h
	.byte	019h,088h,06fh,019h,0d4h,0a9h,009h,000h
	.even

; Compressed string "SMOKE CLEARED, THE UNDERTAKER"
taker_story1_line2
	.byte	0b4h,00bh,0b3h,066h,040h,0b6h,0a6h,038h
	.byte	09bh,065h,013h,0d4h,0a9h,019h,0d8h,06fh
	.byte	069h,0ceh,0b5h,0c8h,09ah,033h,000h
	.even

; Compressed string "STOOD ALONE IN THE SPOTLIGHT,"
taker_story1_line3
	.byte	074h,00dh,0c3h,065h,020h,0b6h,0f0h,06bh
	.byte	006h,0eah,01bh,0d4h,0a9h,019h,0d0h,031h
	.byte	05ch,0b7h,02ah,09ah,0d6h,00dh,000h
	.even

; Compressed string "SILENT.  HE APPROACHED HIS LAST"
taker_story1_line4
	.byte	0b4h,0dah,09ah,06fh,0fdh,004h,041h,06ah
	.byte	006h,062h,01ch,0cfh,0b0h,048h,0a6h,066h
	.byte	019h,0a4h,02ah,01dh,0b4h,022h,05dh,003h
	.even

; Compressed string "VICTIM SLOWLY, KNELT DOWN ON ONE"
taker_story1_line5
	.byte	0b7h,04ah,0d6h,0aah,01bh,0d0h,02dh,08ch
	.byte	0b7h,07ah,013h,0b0h,0afh,0d9h,0d6h,041h
	.byte	009h,0e3h,06fh,000h,0bfh,001h,0fch,09ah
	.byte	000h
	.even

; Compressed string "KNEE AND STARED DEEPLY INTO HIS"
taker_story1_line6
	.byte	0ech,06bh,09ah,081h,0f8h,096h,001h,05dh
	.byte	08bh,0b3h,059h,006h,0a5h,069h,0c6h,0adh
	.byte	01eh,0a8h,06fh,00dh,007h,0a9h,04ah,003h
	.even

; Compressed string "EYES.  IT WAS A STARE SO"
taker_story1_line7
	.byte	0a6h,06eh,0d2h,04fh,010h,0a8h,075h,080h
	.byte	08bh,074h,020h,006h,074h,02dh,0ceh,066h
	.byte	040h,0c3h,000h
	.even

; Compressed string "INTENSE, IT SEEMED TO GO PAST"
taker_story1_line8
	.byte	0eah,05bh,09bh,02fh,06dh,036h,081h,05ah
	.byte	007h,0b4h,069h,0bah,066h,019h,0d4h,070h
	.byte	080h,0c2h,041h,02ch,0d2h,035h,000h
	.even

; Compressed string "THE MAN'S EYES, PAST THE FLESH"
taker_story1_line9
	.byte	075h,06ah,006h,0aeh,0f8h,022h,074h,060h
	.byte	0eah,026h,0ddh,004h,0b1h,048h,0d7h,041h
	.byte	09dh,09ah,0c1h,0d9h,09ah,074h,00ah,000h
	.even

; Compressed string "ITSELF... STRAIGHT TO THE SOUL. "
taker_story1_line10
	.byte	06ah,04dh,09bh,0edh,0f9h,03ch,04fh,040h
	.byte	0d7h,0b3h,0a8h,0a2h,069h,01dh,0d4h,070h
	.byte	050h,0a7h,066h,040h,0c3h,076h,0fbh,004h
	.byte	000h
	.even

; Compressed string "TAKER LOWERED HIS HEAD AND"
taker_story1_line11
	.byte	0b5h,0c8h,09ah,073h,0d0h,0c2h,0b8h,039h
	.byte	09bh,065h,090h,0aah,074h,090h,09ah,062h
	.byte	019h,088h,06fh,009h,000h
	.even

; Compressed string "COVERED THE MAN'S HEART WITH HIS"
taker_story1_line12
	.byte	024h,07ch,09bh,0b3h,059h,006h,075h,06ah
	.byte	006h,0aeh,0f8h,022h,074h,090h,09ah,0e2h
	.byte	05ch,007h,0b8h,05ah,0a7h,041h,0aah,0d2h
	.byte	000h
	.even

; Compressed string "HAND.  THE LIGHTS MYSTERIOUSLY"
taker_story1_line13
	.byte	0a9h,0f8h,096h,04fh,010h,0d4h,0a9h,019h
	.byte	0b4h,02ah,09ah,0d6h,074h,0e0h,0eah,074h
	.byte	06dh,0ceh,02ah,06ch,0d3h,0adh,00eh,000h
	.even

; Compressed string "WENT BLACK, AND ALL THAT COULD"
taker_story1_line14
	.byte	0b8h,0f9h,0d6h,0c1h,0d8h,08ah,024h,0dbh
	.byte	004h,0e2h,05bh,006h,062h,0dbh,006h,075h
	.byte	02ah,0d6h,001h,009h,0dbh,06dh,009h,000h
	.even

; Compressed string "BE SEEN THROUGH THE DARKNESS WAS"
taker_story1_line15
	.byte	0a3h,019h,0d0h,0a6h,0f9h,006h,075h,03ah
	.byte	0c3h,036h,09ah,006h,075h,06ah,006h,0a5h
	.byte	038h,0b3h,0afh,049h,0d3h,001h,02eh,0d2h
	.byte	000h
	.even

; Compressed string "A MIST-LIKE SHAPE RISING UP FROM"
taker_story1_line16
	.byte	062h,0e0h,0aah,074h,0edh,0b4h,02ah,06bh
	.byte	006h,074h,02ah,0c6h,066h,030h,0abh,0b4h
	.byte	0fah,0a2h,081h,01dh,007h,0e7h,00ch,0bbh
	.byte	000h
	.even

; Compressed string "THE BEATEN MAN AND DISSIPATING"
taker_story1_line17
	.byte	075h,06ah,006h,0a3h,029h,0d6h,0e6h,01bh
	.byte	0b8h,0e2h,01bh,088h,06fh,019h,094h,02ah
	.byte	04dh,0abh,0b1h,058h,0abh,02fh,00ah,000h
	.even

; Compressed string "INTO THE UNDERTAKER. WITHOUT ANY"
taker_story1_line18
	.byte	0eah,05bh,0c3h,041h,09dh,09ah,081h,0fdh
	.byte	096h,0e6h,05ch,08bh,0ach,039h,03fh,001h
	.byte	0aeh,0d6h,029h,06ch,0d7h,081h,0f8h,0eah
	.byte	000h
	.even

; Compressed string "HESITATION OR REMORSE, HE DID"
taker_story1_line19
	.byte	0a9h,049h,0abh,0b5h,058h,0abh,0f0h,01bh
	.byte	0c0h,073h,030h,09bh,02eh,03ch,0d3h,066h
	.byte	013h,0a4h,066h,050h,0aah,025h,000h
	.even

; Compressed string "THIS SYSTEMATICALLY TO EACH OF"
taker_story1_line20
	.byte	075h,0aah,0d2h,001h,0adh,0d3h,0b5h,0e9h
	.byte	08ah,0b5h,04ah,08ah,06dh,0abh,007h,035h
	.byte	01ch,098h,022h,099h,006h,0f0h,009h,000h
	.even

; Compressed string "HIS FOES THAT EVENING, AS IF IN"
taker_story1_line21
	.byte	0a9h,04ah,007h,027h,06ch,0d2h,041h,09dh
	.byte	08ah,075h,060h,0deh,0e6h,0abh,0beh,068h
	.byte	013h,088h,074h,0a0h,09eh,081h,0fah,002h
	.even

; Compressed string "SOME HYPNOTIC TRANCE.  IT'S A"
taker_story1_line22
	.byte	034h,0ech,09ah,041h,0aah,0c7h,02fh,05ch
	.byte	0abh,064h,050h,0cfh,0e2h,04bh,09ah,04fh
	.byte	010h,0a8h,035h,042h,007h,022h,000h
	.even

; Compressed string "SHAME, TOO, BECAUSE HE ACTUALLY"
taker_story1_line23
	.byte	074h,02ah,0bah,066h,013h,0d4h,030h,0dch
	.byte	004h,0a3h,049h,08ah,036h,06dh,006h,0a9h
	.byte	019h,088h,064h,06dh,08bh,06dh,0abh,003h
	.even

; Compressed string "LIKED SOME OF THOSE GUYS.  IT'S"
taker_story1_line24
	.byte	0adh,0cah,09ah,065h,040h,0c3h,0aeh,019h
	.byte	0c0h,067h,050h,0a7h,030h,06dh,006h,0a8h
	.byte	0adh,0d3h,04fh,010h,0a8h,035h,042h,003h
	.even

; Compressed string "NOT SURPRISING THOUGH, AS NO ONE"
taker_story1_line25
	.byte	02fh,05ch,007h,0b4h,03dh,0c7h,0b3h,04ah
	.byte	0abh,02fh,01ah,0d4h,029h,06ch,0a3h,069h
	.byte	013h,088h,074h,0f0h,0c2h,001h,0fch,09ah
	.byte	000h
	.even

; Compressed string "EVER COULD UNDERSTAND THE WAYS"
taker_story1_line26
	.byte	0e6h,06dh,0ceh,001h,009h,0dbh,06dh,019h
	.byte	0d8h,06fh,069h,0ceh,074h,02dh,0beh,065h
	.byte	050h,0a7h,066h,080h,08bh,03ah,00dh,000h
	.even

; Compressed string "OF THE UNDERTAKER,  EXCEPT MAYBE"
taker_story1_line27
	.byte	0f0h,019h,0d4h,0a9h,019h,0d8h,06fh,069h
	.byte	0ceh,0b5h,0c8h,09ah,073h,013h,004h,066h
	.byte	04eh,09ah,071h,01dh,0b8h,0a2h,03eh,09ah
	.byte	000h
	.even

; Compressed string "PAUL BEARER. AFTER ALL WAS DONE,"
taker_story1_line28
	.byte	0b1h,068h,0b7h,0c1h,068h,08ah,0b3h,039h
	.byte	03fh,081h,078h,0d6h,0e6h,01ch,088h,06dh
	.byte	01bh,0e0h,022h,01dh,094h,0f0h,06bh,036h
	.byte	000h
	.even

; Compressed string "THE UNDERTAKER DISSAPEARED INTO"
taker_story1_line29
	.byte	075h,06ah,006h,0f6h,05bh,09ah,073h,02dh
	.byte	0b2h,0e6h,01ch,094h,02ah,04dh,08bh,0b1h
	.byte	029h,0ceh,066h,019h,0a8h,06fh,00dh,003h
	.even

; Compressed string "THE BLACKNESS AND HEADED OFF TO"
taker_story1_line30
	.byte	075h,06ah,006h,063h,02bh,092h,0ech,06bh
	.byte	0d2h,074h,020h,0beh,065h,090h,09ah,062h
	.byte	069h,096h,001h,07ch,09eh,041h,00dh,003h
	.even

; Compressed string "DEATH VALLEY, WHERE HE MAY REST"
taker_story1_line31
	.byte	0a5h,029h,0d6h,069h,070h,08bh,06dh,06bh
	.byte	0eah,04dh,080h,0a7h,0e6h,06ch,006h,0a9h
	.byte	019h,0b8h,0a2h,01eh,0cch,026h,05dh,003h
	.even

; Compressed string "IN PEACE."
taker_story1_line32
	.byte	0eah,01bh,0c4h,0a6h,048h,09ah,00fh,000h
	.even

;
; Story line table for Story 1 of taker
;
taker_story_tbl1
	.long	taker_story1_line1
	.long	taker_story1_line2
	.long	taker_story1_line3
	.long	taker_story1_line4
	.long	taker_story1_line5
	.long	taker_story1_line6
	.long	taker_story1_line7
	.long	taker_story1_line8
	.long	taker_story1_line9
	.long	taker_story1_line10
	.long	taker_story1_line11
	.long	taker_story1_line12
	.long	taker_story1_line13
	.long	taker_story1_line14
	.long	taker_story1_line15
	.long	taker_story1_line16
	.long	taker_story1_line17
	.long	taker_story1_line18
	.long	taker_story1_line19
	.long	taker_story1_line20
	.long	taker_story1_line21
	.long	taker_story1_line22
	.long	taker_story1_line23
	.long	taker_story1_line24
	.long	taker_story1_line25
	.long	taker_story1_line26
	.long	taker_story1_line27
	.long	taker_story1_line28
	.long	taker_story1_line29
	.long	taker_story1_line30
	.long	taker_story1_line31
	.long	taker_story1_line32
	.long	0

;
; Table of stories for taker
;
taker_stories
	.long	taker_story_tbl1

