rem ;adam.lod

xcopy s:\usr\mark\video\wwf\img\ADM_HIT.img
xcopy s:\usr\mark\video\wwf\img\ADM_KIK.img
xcopy s:\usr\mark\video\wwf\img\ADM_MSC.img
xcopy s:\usr\mark\video\wwf\img\ADM_PNC.img
xcopy s:\usr\mark\video\wwf\img\ADM_WLK.img

rem ;doink.lod
xcopy s:\usr\mark\video\wwf\img\DNK_HIT.img
xcopy s:\usr\mark\video\wwf\img\DNK_KIK.img
xcopy s:\usr\mark\video\wwf\img\DNK_MSC.img
xcopy s:\usr\mark\video\wwf\img\DNK_PNC.img
xcopy s:\usr\mark\video\wwf\img\DNK_WLK.img

rem ;fonts.lod
xcopy s:\usr\mark\video\wwf\img\credit.img
xcopy s:\usr\mark\video\wwf\img\osgemd.img
xcopy s:\usr\mark\video\wwf\img\ogmd10.img
xcopy s:\usr\mark\video\wwf\img\lgmd.img
xcopy s:\usr\mark\video\wwf\img\sgmd8.img
xcopy s:\usr\mark\video\wwf\img\ogmd10.img
xcopy s:\usr\mark\video\wwf\img\trogf15.img
xcopy s:\usr\mark\video\wwf\img\trogf7.img

rem ;main.lod
xcopy s:\usr\mark\video\wwf\img\diagp.img
xcopy s:\usr\mark\video\wwf\img\arrows.img
xcopy s:\usr\mark\video\wwf\img\wwfstuf.img
xcopy s:\usr\mark\video\wwf\img\pwrbars.img
xcopy s:\usr\mark\video\wwf\img\dcslogo.img
xcopy s:\usr\mark\video\wwf\img\wwfmugs.img
xcopy s:\usr\mark\video\wwf\img\wwfselbk.img
xcopy s:\usr\mark\video\wwf\img\ropestuf.img
xcopy s:\usr\mark\video\wwf\img\ropeshad.img
xcopy s:\usr\mark\video\wwf\img\nmatch12.img
xcopy s:\usr\mark\video\wwf\img\attract.img
xcopy s:\usr\mark\video\wwf\img\NEWRING.bd?
xcopy s:\usr\mark\video\wwf\img\BIOSCRN.bd?
xcopy s:\usr\mark\video\wwf\img\WWFSELBK.bd?

rem ;misc.lod
xcopy s:\usr\mark\video\wwf\img\wwfstuf.img
xcopy s:\usr\mark\video\wwf\img\dcslogo.img
xcopy s:\usr\mark\video\wwf\img\wwfmugs.img
xcopy s:\usr\mark\video\wwf\img\wwfselbk.img

rem ;razor.lod
xcopy s:\usr\mark\video\wwf\img\RZR_HIT.img
xcopy s:\usr\mark\video\wwf\img\RZR_KIK.img
xcopy s:\usr\mark\video\wwf\img\RZR_MSC.img
xcopy s:\usr\mark\video\wwf\img\RZR_PNC.img
xcopy s:\usr\mark\video\wwf\img\RZR_WLK.img

rem ;ref.lod
xcopy s:\usr\mark\video\wwf\img\REF_WLK.img

rem ;robo.lod
xcopy s:\usr\mark\video\wwf\img\robotron.img
